# Generated by Django 2.2.2 on 2020-09-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_auto_20200911_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد موجود در انبار'),
        ),
        migrations.AddField(
            model_name='product',
            name='on_storage',
            field=models.BooleanField(default=True, verbose_name='در انبار موجود میباشد'),
        ),
    ]
