# Generated by Django 2.2.2 on 2020-09-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0007_auto_20200917_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='on_storage',
        ),
    ]
