# Generated by Django 2.2.2 on 2020-09-18 17:03

from django.db import migrations
import django_resized.forms
import eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0009_auto_20200918_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[268, 250], upload_to=eshop_products.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
