# Generated by Django 2.2.2 on 2020-09-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0002_auto_20200916_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
