# Generated by Django 2.2.2 on 2020-09-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='neworder',
            options={'ordering': ('-created',), 'verbose_name': 'سفارش کاربر', 'verbose_name_plural': 'سفارش های کاربران'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'محصول سفارش داده شده', 'verbose_name_plural': 'محصولات سفارش داده شده'},
        ),
        migrations.AddField(
            model_name='neworder',
            name='phone_number',
            field=models.CharField(default=12351, max_length=11, verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neworder',
            name='address',
            field=models.CharField(max_length=250, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='بروز شده'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eshop_order.NewOrder', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='eshop_products.Product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
